// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile/SafferniStackedHomeVariant.tsx": () => import("../components/mockups/mobile/SafferniStackedHomeVariant.tsx"),
  "./components/mockups/mobile/SafferniTravelDesignA.tsx": () => import("../components/mockups/mobile/SafferniTravelDesignA.tsx"),
  "./components/mockups/mobile/SafferniTravelDesignB.tsx": () => import("../components/mockups/mobile/SafferniTravelDesignB.tsx"),
  "./components/mockups/mobile/SafferniTravelDesignC.tsx": () => import("../components/mockups/mobile/SafferniTravelDesignC.tsx"),
  "./components/mockups/templates/DarkLuxuryTravelLandingPage-EX4qEu/Lp06.tsx": () => import("../components/mockups/templates/DarkLuxuryTravelLandingPage-EX4qEu/Lp06.tsx"),
  "./components/mockups/templates/NeonHorizonsTravelCarousel-fMwCLJ/App.tsx": () => import("../components/mockups/templates/NeonHorizonsTravelCarousel-fMwCLJ/App.tsx"),
  "./components/mockups/templates/PatchworkVintageClothingNewsletter-5NyYEz/App.tsx": () => import("../components/mockups/templates/PatchworkVintageClothingNewsletter-5NyYEz/App.tsx")
};
